spring:
  cloud:
    consul:
      port: 8500
      discovery:
        order: 0
        catalog-services-watch-delay: 1000
        catalog-services-watch-timeout: 1000
        register: true
        heartbeat:
          reregister-service-on-failure: false
          enabled: true
          ttl: 30s
        register-health-check: false
        deregister: true
        consistency-mode: consistent
        default-query-tag: admin
        enable-tag-override: true
        enabled: true
        fail-fast: true
        hostname: localhost
        tags: admin,springboot-admin
        service-name: admin
        scheme: http
        query-passing: false
        lifecycle:
          enabled: true
        health-check-interval: 10s
        health-check-timeout: 30s
        health-check-critical-timeout: 60s
      host: 192.168.203.133


