spring:
  application:
    name: EMAIL-SERVICE
  profiles:
    active: predev238
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.qq.com
    username: 2570389155@qq.com
    password: vtmjlxihqxskeada
    default-encoding: UTF-8
    protocol: smtps
  config:
    import:
      - classpath:/application-feign.yml

server:
  port: 18096
management:
  endpoints:
    web:
      exposure:
        include: "*"