spring:
  application:
    name: EMAIL-SERVICE
  profiles:
    active: predev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 18096
management:
  endpoints:
    web:
      exposure:
        include: "*"