spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: email
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path= /email/**
        - id: gw
          uri: lb://gateway
          predicates:
            - Path= /gw/**
        - id: net
          uri: lb://net
          predicates:
            - Path= /net/{segment}
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gateway